### ISSUE TITLE
Errors stating it Requires Missing Libraries

### ISSUE THREAD

**Issue by ranlien** [Mikescher/SynoCtrl#4]
I get the following:

A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/var/tmp/.net/root/synoctrl/y4exlidw.5v2/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64

**Comment by ranlien** [comment]
Found the library now I get the following:

Could not resolve SDK directory from [/usr/bin]

**Comment by Mikescher** [comment]
Wow, this project is 4 years old.

I updated the dependencies and created a new build (worked *suprisingly* well and on the first time...)  
Can you try the binaries from the new [v1.2.0 release](https://github.com/Mikescher/SynoCtrl/releases/tag/v1.2.0)? - At least on my machine the linux-x64-self-contained now works without problems

I probably should update the code a bit for linux, for example to search for the config file somewhere in $HOME/.config - but thats a job for another day (or if you want you can create a PR :D)
